name: Context Variable Demo in Github Actions
on: push 

jobs:
  context-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Use Context Variable
        run: |
          echo "The workflow is triggered by ${{ github.actor }}"
          echo "The repository name is ${{ github.repository }}"

      - name: Print all the variables
        run: echo "${{ github }}"
